name: phone_number_checker
description: "A lightweight Flutter package to detect Nigerian mobile networks (MTN, Airtel, Glo, 9mobile) from phone numbers in local (`080xxxxxxx`) or international (`+23480xxxxxxx`) formats."
version: 0.0.1
homepage: https://github.com/eliteio01/phone_number_checker
repository: https://github.com/eliteio01/phone_number_checker
issue_tracker: https://github.com/eliteio01/phone_number_checker/issues
license: BSD-3-Clause

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


